return {
  "nvim-treesitter/nvim-treesitter",
  highlight = { enable = true },
  indent = { enable = true },
  auto_install = true,
  ensure_installed = {
    "ninja",
    "python",
    "toml",
    "bash",
    "python",
    "dockerfile",
    "hcl",
    "terraform",
    "toml",
    "yaml",
    "html",
    "json",
    "json5",
    "jsonc",
    "cmake",
    "cpp",
    "css",
    "fish",
    "gitignore",
    "go",
    "http",
    "java",
    "php",
    "rust",
    "scss",
    "sql",
  },
}
